//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowbook
    {
        public int borrowid { get; set; }
        public string aridno { get; set; }
        public int isbn { get; set; }
        public System.DateTime issuedate { get; set; }
        public System.DateTime returndate { get; set; }
        public System.DateTime actualreturndate { get; set; }
        public Nullable<decimal> fineamount { get; set; }
        public string status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
