//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Borrowbooks = new HashSet<Borrowbook>();
        }
    
        public string aridno { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string section { get; set; }
        public string degree { get; set; }
        public Nullable<int> semester { get; set; }
        public string city { get; set; }
        public string image { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Borrowbook> Borrowbooks { get; set; }
    }
}
